// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using AutopilotQuick.Quicktype;
//
//    var dellBiosCatalogSettings = DellBiosCatalogSettings.FromJson(jsonString);

namespace AutopilotQuick.Quicktype
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class DellBiosCatalogSettings
    {
        [JsonProperty("CatalogName")]
        public string CatalogName { get; set; }

        [JsonProperty("CatalogUri")]
        public Uri CatalogUri { get; set; }
    }

    public partial class DellBiosCatalogSettings
    {
        public static DellBiosCatalogSettings FromJson(string json) => JsonConvert.DeserializeObject<DellBiosCatalogSettings>(json, AutopilotQuick.Quicktype.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this DellBiosCatalogSettings self) => JsonConvert.SerializeObject(self, AutopilotQuick.Quicktype.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}