name: Beta releases

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    permissions:
        issues: write
        pull-requests: write
        contents: write
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: "Get Previous tag"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: dotnet restore "AutopilotQuick\AutopilotQuick.csproj"

      - name: Publish
        run: |
          dotnet publish "AutopilotQuick\AutopilotQuick.csproj" -p:PublishProfile=DevProfile -p:AssemblyVersion=${{ steps.previoustag.outputs.tag }}.1

      - name: Relocate
        run: |
          mv AutopilotQuick\\bin\\Release\\net6.0-windows\\publish\\AutopilotQuick.exe ..\AutopilotQuick-Beta.exe
      - name: Zip
        run: |
          7z a ..\AutopilotQuick-beta.zip ..\AutopilotQuick-Beta.exe -mx=9    
      
      - name: Upload beta zip
        uses: actions/upload-artifact@v2
        with:
          name: AutopilotQuick-Beta
          path: AutopilotQuick-Beta.zip
