name: goreleaser

on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    permissions:
        issues: write
        pull-requests: write
        contents: write
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: dotnet restore "AutopilotQuick\AutopilotQuick.csproj"
      - name: Publish
        run: |
          dotnet publish "AutopilotQuick\AutopilotQuick.csproj" -p:PublishProfile=PubProfile -p:AssemblyVersion=${{ github.ref_name }}.0
      - name: Relocate
        run: |
          mv AutopilotQuick\\bin\\Release\\net6.0-windows\\publish\\AutopilotQuick.exe ..\AutopilotQuick.exe
      - name: Zip
        run: |
          7z a ..\AutopilotQuick.zip ..\AutopilotQuick.exe -mx=0
      - name: Sign
        uses: carbonneuron/GHActionSignHash@v5
        env: 
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        id: sign
        with:
          path: ../AutopilotQuick.zip
          key: ${{ secrets.PRIVATE_KEY }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Output Signature
        shell: bash
        run: |
          echo "${{ steps.sign.outputs.encrypted-text }}" > ../AutopilotQuick.zip.sha256.pgp
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ github.ref }}
          omitBody: true
          skipIfReleaseExists: true
          artifacts: "../AutopilotQuick.zip,../AutopilotQuick.zip.sha256.pgp"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
